apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
spec:
   replicas: 1
   template:
      spec:
         containers:
            - name: backend
              image: node
              imagePullPolicy: Never
