version: '3'
services:
  backend:
    image: christianp01/cas_backend:latest
    network_mode: host
    command: npm start
    container_name: backend

  database:
    image: postgis/postgis
    environment:
      - PGDATA=/var/lib/pgsql/data
      - POSTGRES_PASSWORD=contextawarerc
    volumes:
      - ./postgres_data:/var/lib/pgsql/data
    network_mode: host
    container_name: database

  frontend:
    image: christianp01/cas_frontend:latest
    network_mode: host
    working_dir: /frontend
    command: npm start
    container_name: frontend
