apiVersion: v1
kind: Service
metadata:
  name: backend-np
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: backend-np
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002
---
apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
spec:
  hostNetwork: true
  containers:
    - name: backend
      image: localbackend
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      # volumeMounts:
      #   - mountPath: /backend
      #     name: backend-data
  # volumes:
  #   - name: backend-data
  #     hostPath:
  #       path: /cas/backend
