apiVersion: v1
kind: Service
metadata:
  name: database-np
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: database-pod
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30001
---
apiVersion: v1
kind: Pod
metadata:
  name: database-pod
spec:
  hostNetwork: true
  containers:
    - name: database
      image: postgis/postgis:15-3.4
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-db
      ports:
        - containerPort: 5432
          name: "postgres"
      env:
        - name: POSTGRES_DB
          value: contextawarerc
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
  volumes:
    - name: postgres-db
      hostPath:
        path: /cas/postgres_data
