apiVersion: v1
kind: Service
metadata:
  name: frontend-np
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: frontend-np
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30003
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
spec:
  hostNetwork: true
  containers:
    - name: frontend
      image: localfrontend
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000